### ISSUE TITLE
For us beginners

### ISSUE THREAD

**Issue by dougbrouwer** [jessicalh/ekmmeters#3]
I think it would be helpful to explain, in the Getting Started part, that one needs to do the pip install ekmmeters, cd to the ekmmeters directory (in my case it went to Documents), and edit the unittest.ini file.

**Comment by jessicalh** [comment]
My observation is that other distros tend to require only the imports necessary for the working module.  The reason being apparent in our BSD experiences -- the more imports along for the ride, the more potential issues with what is a very portable module otherwise.  Unit tests uses ConfigParser and random and a few other things.   When importlib is gone, ekmmeters will require only struct and json and OrderedDict outside of the "comes with python" stuff (and the last would go away if we didn't require python 2.6 to work)

I think that a unit tests -- ini and imports -- might be appropriate to the introduction?  How to use unit tests if you are modifying the code.  As mentioned, every unit test is reflected (without assertions or test framework stuff) in the examples, which are made for human consumers.

**Comment by jessicalh** [comment]
OK.  There is now a docs section for the unit test, at the top level, with an appropriate explanation..  And the unit test, which was fully and carefully supplanted by the examples, is not mentioned in getting started.   We can discuss and reopen if appropriate.
